name: Validator CI check

on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: checkout this repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: checkout validator repo
        uses: actions/checkout@v3
        with:
          repository: CMSgov/price-transparency-guide-validator
          path: validator
      - name: initialize validator submodules
        working-directory: ./validator
        run: |
          git submodule init
          git submodule update --remote --merge
      - name: build validator docker image
        run: docker build -t validator validator/
      - name: install validator node script
        run: npm install -g cms-mrf-validator
      - name: update validator schemas
        run: cms-mrf-validator update
      - name: test in-network rates examples
        run: |
          cms-mrf-validator validate main/examples/in-network-rates/in-network-rates-bundle-single-plan-sample.json --schema-version v1.6.1 -y
          cms-mrf-validator validate main/examples/in-network-rates/in-network-rates-capitation-single-plan-sample.json --schema-version v1.6.1 -y
          cms-mrf-validator validate main/examples/in-network-rates/in-network-rates-fee-for-service-single-plan-sample.json --schema-version v1.6.1 -y
          cms-mrf-validator validate main/examples/in-network-rates/in-network-rates-multiple-plans-sample.json --schema-version v1.6.1 -y
          cms-mrf-validator validate main/examples/in-network-rates/in-network-rates-no-npi.json --schema-version v1.6.1 -y
