name: Validator CI check

on: [workflow_dispatch, push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: checkout this repo
        uses: actions/checkout@v3
        with:
          path: main
      - name: checkout validator repo
        uses: actions/checkout@v3
        with:
          repository: CMSgov/price-transparency-guide-validator
          path: validator
      - name: initialize validator submodules
        working-directory: ./validator
        run: |
          git submodule init
          git submodule update --remote --merge
      - name: build validator docker image
        run: docker build -t validator validator/
      - name: install validator node script
        run: npm install -g cms-mrf-validator
      - name: update validator schemas
        run: cms-mrf-validator update
      - name: test allowed-amounts examples
        run: find main/examples/allowed-amounts/ -name *.json -print0 | xargs -0 -n 1 cms-mrf-validator validate --schema-version v1.6.1 -t allowed-amounts -y
      - name: test in-network-rates examples
        run: find main/examples/in-network-rates/ -name *.json -print0 | xargs -0 -n 1 cms-mrf-validator validate --schema-version v1.6.1 -t in-network-rates -y
      - name: test provider-reference examples
        run: find main/examples/provider-reference/ -name *.json -print0 | xargs -0 -n 1 cms-mrf-validator validate --schema-version v1.6.1 -t provider-reference -y
      - name: test table-of-contents examples
        run: find main/examples/table-of-contents/ -name *.json -print0 | xargs -0 -n 1 cms-mrf-validator validate --schema-version v1.6.1 -t table-of-contents -y
